name: RepoSync master-dan
on:
 workflow_dispatch:
 schedule:
   - cron:  "20 22-23 * * *"

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 2
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "CSSEGISandData/COVID-19"
        source_branch: "master"
        destination_branch: "master-dan"
        github_token: ${{ secrets.GITHUB_TOKEN }}
