name: RepoSync web-data
on:
  schedule:
  - cron:  "*/45 * * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "CSSEGISandData/COVID-19"
        source_branch: "web-data"
        destination_branch: "web-data"
        github_token: ${{ secrets.GITHUB_TOKEN }}
