name: RepoSync web-data
on:
  schedule:
   - cron:  "35 */1 * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "CSSEGISandData/COVID-19"
        source_branch: "web-data"
        destination_branch: "web-data"
        github_token: ${{ secrets.GITHUB_TOKEN }}
