name: RepoSync master-dan
on:
  schedule:
   - cron:  "5 22-23 * * *"
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "CSSEGISandData/COVID-19"
        source_branch: "master"
        destination_branch: "master-dan"
        github_token: ${{ secrets.GITHUB_TOKEN }}
