name: RepoSync master-dan
on:
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ZamulaK/COVID-19
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Sync
      uses:  denis-tingajkin/sync-files@main
      with:
        git-author-email: 'dan@dan.com'
        git-author-name: 'Dan'
        src-repository: CSSEGISandData/COVID-19
        allow-files-pattern: csse_covid_19_data/*
        sync-branch-name: master
        result-branch-name: master-dan
